name:                aoc
version:             0.1.0.0
github:              "RikvanToor/aoc"
license:             BSD3
author:              "Rik van Toor"
maintainer:          "rik@rikvantoor.nl"
copyright:           "2020 Rik van Toor"

extra-source-files:
- README.md
- data/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- linear >= 1.21
- parsec
- gloss
- grids

library:
  source-dirs: src

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc